language: node_js
node_js:
  - "node"

cache:
  directories:
    - $HOME/.npm

script:
  - cd client
  - npm ci -q
  - npm run build
  - echo "hk.xaked.com" > build/CNAME
  - cd ../ && echo "${HEROKU_LOGIN}" | base64 -d >> ~/.netrc
  - git init
  - heroku git:remote -a dry-reaches-96843
  - git add .
  - git commit -am 'Heroku deployment'
  - git push --force heroku master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: client/build
  target_branch: gh-pages
  on:
    branch: master